### ISSUE TITLE
Themen ausformulieren (Sätze)

### ISSUE THREAD

**Issue by HeidiSeibold** [BERD-NFDI/ADA-Oeffentliche-Verwaltung-Website#11]
Statt "Intro" eher "Einführung in die Workshop-Serie." usw.

Gerne auch mit einem einleitenden Satz, wie "In Modul 2 arbeiten wir mit den Daten. Es werden keine Vorkenntnisse in Datenanalyse erwarten. Sie können sich auf folgende Themen freuen:".

**Comment by MaxMLang** [comment]
Yes.
