### ISSUE TITLE
Bilder für Modul 2

### ISSUE THREAD

**Issue by HeidiSeibold** [BERD-NFDI/ADA-Oeffentliche-Verwaltung-Website#12]
Hi @malsch und @mneunhoe, habt ihr Bilder, die wir repräsentativ für Modul 2 auf die Website packen könnten?

**Comment by malsch** [comment]
ein Diagramm wie unter https://eo-vmw-jwpa.ku.de/journalistik/methoden/auswahlarten/#geschichtet fände ich gut.

**Comment by HeidiSeibold** [comment]
@MaxMLang ich glaub hier müssen wir zitieren woher wir das Bild haben.
