### ISSUE TITLE
Bilder für Modul 3

### ISSUE THREAD

**Issue by HeidiSeibold** [BERD-NFDI/ADA-Oeffentliche-Verwaltung-Website#13]
Hi @malsch und @fkreuter, habt ihr Ideen für Bilder, die man für Modul 3 auf die Website packen könnte?

**Comment by MaxMLang** [comment]
Ich hab jetzt einfach mal ein Shiny Dashboard hingepackt. Falls es Änderungswünsche gibt let me know

**Comment by HeidiSeibold** [comment]
@malsch und @fkreuter schickt uns gerne noch bessere Bilder hierfür. 

Im Notebook werden ja auch schöne Grafiken erzeugt, die man hier sicher einfügen könnte, oder?
