### ISSUE TITLE
References Seite löschen

### ISSUE THREAD

**Issue by HeidiSeibold** [BERD-NFDI/ADA-Oeffentliche-Verwaltung-Website#4]
https://berd-nfdi.github.io/ADA-Oeffentliche-Verwaltung-Website/references.html

Brauchen wir glaube ich nicht, oder?

**Comment by MaxMLang** [comment]
Quellen könnte man im Einzelfall einfach mit einer Fußnote auf der jeweiligen Seite hinzufügen. Hab die Seite rausgenommen.
