### ISSUE TITLE
Lernziele auf der Website anpassen

### ISSUE THREAD

**Issue by HeidiSeibold** [BERD-NFDI/ADA-Oeffentliche-Verwaltung-Website#5]
Die Lernziele, die gerade auf der Website sind, sind eigentlich keine richtigen Lernziele. Ich kümmere mich darum, dass richtige Lernziele formuliert werden 😉. Dann gerne anpassen.

**Comment by MaxMLang** [comment]
Ich hab die Lernziele bereits in ein einheitliches Format gebracht, falls zu den anderen Modulen es noch Input gibt let me know,.

**Comment by HeidiSeibold** [comment]
Ich habe da jetzt nochmal ausgebessert und denke, es passt fürs erste.
